### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/z3c.autoinclude#17]
I'd like to cut a new release of this repository. Could you please give me (`icemac`) PyPI maintainer rights?

Cc-ing some of the current maintainers:

@davisagli @esteele @janjaapdriessen @janwijbrand @mgedmin

**Comment by janwijbrand** [comment]
done

**Comment by icemac** [comment]
Thank you. I just released https://pypi.org/project/z3c.autoinclude/1.0/.
